services:
  - type: web
    name: student-management-django
    env: python
    region: singapore
    buildCommand: "./build.sh"
    startCommand: "gunicorn student_project.wsgi:application"
    plan: free
